### ISSUE TITLE
To Do List > Icon when list is open 

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#18]
When the to do list is open the icon is too close to the checkmark. Need a solution for this. Not sure I like having the icon there when the list is open. 

![screen shot 2014-10-12 at 4 14 53 pm](https://cloud.githubusercontent.com/assets/7152379/4607370/9bf81266-524c-11e4-96f0-64bb4be4ccbf.png)

**Comment by GarrethDottin** [comment]
No longer a priority
