### ISSUE TITLE
To Do List > Scrolling

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#19]
The to do list will not scroll if too many tasks are inputted. They will just be hidden below the fold. 

![screen shot 2014-10-13 at 10 38 09 pm](https://cloud.githubusercontent.com/assets/7152379/4623306/33ee401e-534b-11e4-95eb-825d671dd0c4.png)

**Comment by GarrethDottin** [comment]
Issue is addressed in another ticket
