### ISSUE TITLE
To Do List > Can't put in long tasks

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#39]
The character count is too short on the To Do list. There is a way around this count. If you put in a task and then go back and edit there will be no limit . We need to find a more elegant solution for longer task input. 

![screen shot 2014-12-11 at 4 29 07 pm](https://cloud.githubusercontent.com/assets/7152379/5402463/df155628-8152-11e4-95ab-57d9257ace23.png)

**Comment by GarrethDottin** [comment]
Character count limited across everything
