### ISSUE TITLE
To Do List > Blank Spot

### ISSUE THREAD

**Issue by Ryan-Parker** [GarrethDottin/Ps#56]
Sometimes a blank spot will be left on the task list when you check off multiple tasks at once. The task is still present and will show once the page reloads. 

![screen shot 2015-01-03 at 3 03 26 pm](https://cloud.githubusercontent.com/assets/7152379/5603576/c6679d52-9359-11e4-9497-d4aeec3b25a3.png)

**Comment by GarrethDottin** [comment]
No longer an issue
