### ISSUE TITLE
To Do - Inconsistent behavior when clicking To Do

### ISSUE THREAD

**Issue by JVeerman** [GarrethDottin/Ps#58]
1. (Assume all tickets I create start from the homepage) On first page load, click TO DO
2. Click the TO DO again to retract the popout menu
3. Click TO DO again

Output: The body content is no longer being resized. The popout is overlapping the buttons.
Browser: Chrome 39

Initial page load:
![2015-01-11 16_42_34-grooveotter](https://cloud.githubusercontent.com/assets/5413424/5696968/36392148-99b1-11e4-97af-909015f9d40a.jpg)

Subsequent page load:
![2015-01-11 16_43_07-grooveotter](https://cloud.githubusercontent.com/assets/5413424/5696969/37871244-99b1-11e4-9f47-1487300d97e1.jpg)

**Comment by GarrethDottin** [comment]
expected behavior
