### ISSUE TITLE
To Do - Suggestion - Whitespace is limiting the number of tasks that are displayed

### ISSUE THREAD

**Issue by JVeerman** [GarrethDottin/Ps#67]
If the white space and the padding around Today and Completed were reduced, the page would be able to display more items.

![7 - whitespace](https://cloud.githubusercontent.com/assets/5413424/5697123/b28d303c-99b5-11e4-9192-42f61cce40bd.jpg)

**Comment by GarrethDottin** [comment]
Agreed working on that this week
